/**
 * Planet-in-house interpretations (Graha Bhavaphala).
 *
 * Each entry: what a specific planet means when placed in a specific house.
 * Keyed by planetId (0-11) and house number (1-12).
 */
export type PlanetInHouseEntry = {
  planetId: number;
  house: number;
  effect: "beneficial" | "challenging" | "neutral" | "mixed";
  interpretation: { en: string; si: string };
  career: { en: string; si: string };
  relationships: { en: string; si: string };
  health: { en: string; si: string };
};

// We store English only for now; Sinhala can be added later
export type PlanetInHouseEntrySimple = {
  planetId: number;
  house: number;
  effect: "beneficial" | "challenging" | "neutral" | "mixed";
  interpretation: string;
  career: string;
  relationships: string;
  health: string;
};

const PLANET_IN_HOUSE: PlanetInHouseEntrySimple[] = [
  // ────────── SUN (0) ──────────
  { planetId: 0, house: 1, effect: "beneficial", interpretation: "Strong personality, leadership qualities, confident, authoritative. Good health and vitality.", career: "Natural leader, management roles, government positions.", relationships: "Dominant in relationships, protective but may be egoistic.", health: "Generally strong health, prone to heart Issues if afflicted." },
  { planetId: 0, house: 2, effect: "beneficial", interpretation: "Wealthy, well-spoken, influential family background. Good with finances.", career: "Finance, public speaking, teaching, oratory.", relationships: "Family-oriented, generous with loved ones.", health: "Prone to throat Issues, eye strain." },
  { planetId: 0, house: 3, effect: "neutral", interpretation: "Courageous, independent, strong-willed. Good relationship with siblings.", career: "Military, sports, engineering, entrepreneurship.", relationships: "Energetic with siblings, may have conflicts with neighbors.", health: "Prone to headaches, nervous tension." },
  { planetId: 0, house: 4, effect: "beneficial", interpretation: "Educated, comfortable home life, property ownership. Strong maternal bond.", career: "Real estate, education, farming, hospitality.", relationships: "Loving mother, harmonious domestic life.", health: "Chest and heart need attention." },
  { planetId: 0, house: 5, effect: "beneficial", interpretation: "Creative, intelligent, good with children. Speculative gains.", career: "Creative fields, teaching, stock market, entertainment.", relationships: "Loving parent, romantic nature.", health: "Generally healthy, heart-related issues possible." },
  { planetId: 0, house: 6, effect: "challenging", interpretation: "Enemies, debts, health issues. Litigation-prone. Overcomes obstacles through willpower.", career: "Law, healthcare, military, competitive fields.", relationships: "Prone to conflicts with colleagues.", health: "Chronic health issues that require discipline to manage." },
  { planetId: 0, house: 7, effect: "neutral", interpretation: "Strong marriage partner, public recognition. May marry someone authoritative.", career: "Public relations, partnerships, consulting.", relationships: "Spouse is strong-willed, partnership is public-facing.", health: "Health tied to partner's well-being." },
  { planetId: 0, house: 8, effect: "challenging", interpretation: "Longevity challenges, hidden knowledge, interest in occult. Sudden events.", career: "Research, investigation, occult sciences, insurance.", relationships: "Intense, transformative relationships. Secrets in marriage.", health: "Chronic issues, recovery from serious illness." },
  { planetId: 0, house: 9, effect: "beneficial", interpretation: "Righteous, spiritual, fortunate. Good relationship with father. Higher education.", career: "Teaching, religion, law, publishing, travel industry.", relationships: "Wise, respected. Good relationship with father figure.", health: "Good health, prone to thigh-related Issues." },
  { planetId: 0, house: 10, effect: "beneficial", interpretation: "High career achievement, fame, authority. Recognition and status.", career: "Government, leadership, management, public office.", relationships: "Marriage to someone career-oriented.", health: "Stress-related Issues from work pressure." },
  { planetId: 0, house: 11, effect: "beneficial", interpretation: "High income, many friends, fulfilled desires. Social success.", career: "Networking, sales, large organizations.", relationships: "Many influential friends, helpful social circle.", health: "Good health, minor leg Issues." },
  { planetId: 0, house: 12, effect: "challenging", interpretation: "Expenditure, foreign travel, spiritual inclination. Loss of father early.", career: "Foreign work, hospitals, spiritual institutions.", relationships: "Isolation in relationships, spiritual detachment.", health: "Prone to hospitalization, foot Issues, eye weakness." },

  // ────────── MOON (1) ──────────
  { planetId: 1, house: 1, effect: "beneficial", interpretation: "Emotional, intuitive, nurturing personality. Good memory and imagination.", career: "Creative arts, counseling, healthcare, hospitality.", relationships: "Caring partner, emotionally expressive.", health: "Prone to water retention, mood-related health Issues." },
  { planetId: 1, house: 2, effect: "beneficial", interpretation: "Wealthy family, good speech, enjoyer of fine things. Financial fluctuations.", career: "Food industry, finance, public speaking.", relationships: "Close family bonds, loving spouse.", health: "Prone to digestive Issues, sensitivity to food." },
  { planetId: 1, house: 3, effect: "neutral", interpretation: "Changeable mind, artistic, good with communication. Wandering nature.", career: "Writing, media, travel industry, performing arts.", relationships: "Close to siblings, many neighbors.", health: "Lung sensitivity, mood-related breathing Issues." },
  { planetId: 1, house: 4, effect: "beneficial", interpretation: "Loving home, good mother, property owner. Emotional security.", career: "Real estate, farming, home-based business.", relationships: "Deep bond with mother, nurturing home life.", health: "Good health, chest comfort." },
  { planetId: 1, house: 5, effect: "beneficial", interpretation: "Creative, intelligent, good with children. Emotional fulfillment.", career: "Creative arts, teaching children, entertainment.", relationships: "Loving parent, romantic and affectionate.", health: "Good health, heart sensitive to emotional state." },
  { planetId: 1, house: 6, effect: "challenging", interpretation: "Health worries, conflicts, emotional stress from competition.", career: "Healthcare, social work, service industry.", relationships: "Strained relationships with colleagues.", health: "Digestive Issues from stress, fluctuating health." },
  { planetId: 1, house: 7, effect: "neutral", interpretation: "Emotional marriage, public popularity. Partnership with caring person.", career: "Public relations, hospitality, counseling.", relationships: "Sensitive spouse, marriage influenced by emotions.", health: "Psychosomatic Issues, health affected by relationship." },
  { planetId: 1, house: 8, effect: "challenging", interpretation: "Intense emotions, psychic tendencies, interest in mysteries.", career: "Occult research, psychology, investigation.", relationships: "Deep but turbulent relationships. Secretive tendencies.", health: "Chronic health Issues, mental health sensitivity." },
  { planetId: 1, house: 9, effect: "beneficial", interpretation: "Spiritual, philosophical, good fortune through teachers.", career: "Teaching, publishing, travel, spirituality.", relationships: "Respected, wise. Good relationship with gurus.", health: "Good overall health." },
  { planetId: 1, house: 10, effect: "beneficial", interpretation: "Public popularity, career in public service, emotional connection to work.", career: "Public relations, politics, arts, counseling.", relationships: "Emotional investment in career affects relationships.", health: "Stress from public life." },
  { planetId: 1, house: 11, effect: "beneficial", interpretation: "Many friends, fulfilled wishes, emotional satisfaction from social circle.", career: "Social media, networking, community work.", relationships: "Popular, helpful friends, social success.", health: "Good health." },
  { planetId: 1, house: 12, effect: "challenging", interpretation: "Emotional spending, foreign travel, spiritual withdrawal.", career: "Spiritual work, institutions, foreign employment.", relationships: "Emotional isolation, need for solitude.", health: "Sleep Issues, mental health needs attention." },

  // ────────── MERCURY (2) ──────────
  { planetId: 2, house: 1, effect: "beneficial", interpretation: "Intelligent, witty, good communicator. Adaptable personality.", career: "Writing, teaching, IT, media, consulting.", relationships: "Intellectually stimulating, good conversationalist.", health: "Prone to nervous tension, skin sensitivity." },
  { planetId: 2, house: 2, effect: "beneficial", interpretation: "Eloquent speaker, writer, good financial sense. Business acumen.", career: "Finance, writing, teaching, sales.", relationships: "Articulate, good family communication.", health: "Prone to speech Issues, throat sensitivity." },
  { planetId: 2, house: 3, effect: "beneficial", interpretation: "Excellent communication with siblings, skilled writer, clever.", career: "Writing, journalism, marketing, IT.", relationships: "Close with siblings, strong local network.", health: "Nervous system needs care." },
  { planetId: 2, house: 4, effect: "beneficial", interpretation: "Intellectual home, educated, real estate skills. Good memory.", career: "Education, real estate, publishing.", relationships: "Intellectual family environment.", health: "Chest and lung sensitivity." },
  { planetId: 2, house: 5, effect: "beneficial", interpretation: "Highly intelligent, creative writer, good with children and speculation.", career: "Teaching, writing, stock market, creative arts.", relationships: "Mentor to children, playful in romance.", health: "Good health, mind-body connection strong." },
  { planetId: 2, house: 6, effect: "neutral", interpretation: "Analytical, good at strategy, competitive. Overcomes rivals through wit.", career: "Law, accounting, medicine, analysis.", relationships: "Argumentative tendencies, intellectual rivalries.", health: "Digestive Issues from overthinking." },
  { planetId: 2, house: 7, effect: "beneficial", interpretation: "Intellectual partnership, communicative marriage. Business partnerships.", career: "Public relations, consulting, mediation.", relationships: "Marriage to someone intelligent and communicative.", health: "Stress from overworking." },
  { planetId: 2, house: 8, effect: "challenging", interpretation: "Keen researcher, investigator, secretive. Interest in hidden knowledge.", career: "Research, detective work, occult studies.", relationships: "Secretive relationships, intellectual mystery.", health: "Prone to nervous disorders, anxiety." },
  { planetId: 2, house: 9, effect: "beneficial", interpretation: "Learned, philosophical, good teacher. Higher education success.", career: "Teaching, publishing, philosophy, law.", relationships: "Respected teacher, wise counselor.", health: "Generally healthy." },
  { planetId: 2, house: 10, effect: "beneficial", interpretation: "Career in communication, media, IT. Business success through intellect.", career: "Media, publishing, technology, consulting.", relationships: "Professional network strong, work relationships good.", health: "Stress from mental overactivity." },
  { planetId: 2, house: 11, effect: "beneficial", interpretation: "Income through intellect, many friends in intellectual circles.", career: "Networking, sales, writing, social media.", relationships: "Many friends, intellectual social circle.", health: "Good health." },
  { planetId: 2, house: 12, effect: "challenging", interpretation: "Spending on education, foreign communication, interest in spirituality.", career: "Translation, foreign work, spiritual teaching.", relationships: "Detached communication, isolation tendencies.", health: "Lung sensitivity, sleep Issues." },

  // ────────── VENUS (3) ──────────
  { planetId: 3, house: 1, effect: "beneficial", interpretation: "Attractive, charming, artistic. Loving personality, luxury-loving.", career: "Arts, beauty, fashion, entertainment.", relationships: "Romantic, affectionate, popular.", health: "Prone to reproductive system Issues, sweet cravings." },
  { planetId: 3, house: 2, effect: "beneficial", interpretation: "Wealthy, beautiful speech, artistic family. Enjoyer of luxuries.", career: "Finance, arts, beauty industry.", relationships: "Expressive love, family enjoys comfort.", health: "Throat sensitivity, diabetes risk." },
  { planetId: 3, house: 3, effect: "beneficial", interpretation: "Artistic expression, musical talent, good with hands. Creative hobbies.", career: "Music, arts, dance, creative writing.", relationships: "Harmony with siblings, artistic partners.", health: "Good health." },
  { planetId: 3, house: 4, effect: "beneficial", interpretation: "Beautiful home, artistic environment, comfortable life. Vehicle enjoyment.", career: "Real estate, interior design, art dealing.", relationships: "Loving family, harmonious domestic life.", health: "Chest health good." },
  { planetId: 3, house: 5, effect: "beneficial", interpretation: "Creative, romantic, good with children. Artistic talent, speculative gains.", career: "Creative arts, entertainment, romance counseling.", relationships: "Romantic, loving parent, passionate.", health: "Good health, reproductive health strong." },
  { planetId: 3, house: 6, effect: "challenging", interpretation: "Luxury expenses, relationship with competitors. Artistic service.", career: "Beauty services, hospitality, counseling.", relationships: "Relationships with colleagues, service through love.", health: "Prone to diabetes, sweet-related Issues." },
  { planetId: 3, house: 7, effect: "beneficial", interpretation: "Beautiful marriage, loving partner. Harmonious relationships.", career: "Counseling, partnerships, public relations.", relationships: "Romantic marriage, attractive spouse.", health: "Health tied to partner's well-being." },
  { planetId: 3, house: 8, effect: "challenging", interpretation: "Hidden relationships, secrets in marriage. Interest in occult arts.", career: "Investigative work, occult arts, therapy.", relationships: "Intense love life, secret affairs possible.", health: "Reproductive health Issues." },
  { planetId: 3, house: 9, effect: "beneficial", interpretation: "Spiritual, artistic philosophy, fortunate in travel. Good dharma.", career: "Art education, spiritual teaching, travel.", relationships: "Wise in relationships, artistic partner.", health: "Good health." },
  { planetId: 3, house: 10, effect: "beneficial", interpretation: "Career in arts, beauty, luxury goods. Public popularity.", career: "Arts, entertainment, luxury brands, beauty.", relationships: "Relationships support career.", health: "Good health, active social life." },
  { planetId: 3, house: 11, effect: "beneficial", interpretation: "Income through arts, many friends, fulfilled desires for luxury.", career: "Arts, social media, networking.", relationships: "Popular, artistic friends.", health: "Good health." },
  { planetId: 3, house: 12, effect: "challenging", interpretation: "Expenditure on luxuries, foreign romance. Spiritual love.", career: "Spiritual work, foreign business, luxury imports.", relationships: "Romantic overseas, secret love affairs.", health: "Hospitalization possible, reproductive care needed." },

  // ────────── MARS (4) ──────────
  { planetId: 4, house: 1, effect: "beneficial", interpretation: "Courageous, energetic, assertive. Natural leader, competitive spirit.", career: "Military, sports, engineering, leadership roles.", relationships: "Passionate, may be aggressive. Needs control.", health: "Prone to accidents, fever, inflammation." },
  { planetId: 4, house: 2, effect: "challenging", interpretation: "Harsh speech, financial arguments, family conflicts.", career: "Surgery, military, competitive finance.", relationships: "Arguments over money, family disputes.", health: "Prone to accidents face/teeth." },
  { planetId: 4, house: 3, effect: "beneficial", interpretation: "Courageous, protective of siblings, skilled with tools.", career: "Military, engineering, sports, skilled trades.", relationships: "Protective of siblings, competitive with neighbors.", health: "Good energy, accident-prone hands." },
  { planetId: 4, house: 4, effect: "challenging", interpretation: "Conflicts at home, issues with mother, property disputes.", career: "Real estate disputes, construction, military.", relationships: "Strained family relations, conflict with mother.", health: "Chest Issues, heart problems if afflicted." },
  { planetId: 4, house: 5, effect: "challenging", interpretation: "Aggressive in romance, issues with children. Speculative losses.", career: "Competitive fields, stock market, gambling.", relationships: "Intense romance, strict parent.", health: "Prone to fever, infections." },
  { planetId: 4, house: 6, effect: "beneficial", interpretation: "Victory over enemies, strong competitor, good health. Martial energy.", career: "Military, law enforcement, sports, surgery.", relationships: "Commanding presence, respected by rivals.", health: "Strong health, recovers quickly." },
  { planetId: 4, house: 7, effect: "challenging", interpretation: "Conflict in marriage, aggressive partner. Mangalik dosha if in 1/2/4/7/8/12.", career: "Competitive partnerships, legal work.", relationships: "Marital conflicts, passionate but volatile.", health: "Partner's health may be affected." },
  { planetId: 4, house: 8, effect: "challenging", interpretation: "Hidden anger, accidents, sudden events. Interest in occult.", career: "Surgery, investigation, military, occult.", relationships: "Intense secret relationships, sudden breakups.", health: "Accident-prone, surgery likely." },
  { planetId: 4, house: 9, effect: "beneficial", interpretation: "Brave in beliefs, protective of religion/philosophy. Adventurous.", career: "Law, religion, military, adventure sports.", relationships: "Protective of loved ones' beliefs.", health: "Good health, active lifestyle." },
  { planetId: 4, house: 10, effect: "beneficial", interpretation: "High career achievement, ambitious, competitive success.", career: "Leadership, politics, military, entrepreneurship.", relationships: "Intense career focus affects relationships.", health: "Stress from overwork, accident risk." },
  { planetId: 4, house: 11, effect: "beneficial", interpretation: "Income through bold ventures, influential friends.", career: "Entrepreneurship, competitive sales.", relationships: "Friends from competitive fields.", health: "Good health." },
  { planetId: 4, house: 12, effect: "challenging", interpretation: "Expenditure on conflicts, foreign travel for work. Surgery possible.", career: "Military abroad, surgery, foreign work.", relationships: "Separations in relationships.", health: "Hospitalization, surgery, foot injuries." },

  // ────────── JUPITER (5) ──────────
  { planetId: 5, house: 1, effect: "beneficial", interpretation: "Wise, optimistic, generous. Natural teacher. Good fortune.", career: "Teaching, counseling, law, finance.", relationships: "Wise partner, optimistic outlook.", health: "Good health, prone to weight gain." },
  { planetId: 5, house: 2, effect: "beneficial", interpretation: "Wealthy, generous, wise speech. Family prosperity.", career: "Finance, law, education, counseling.", relationships: "Generous with family, wise advisor.", health: "Prone to diabetes, good metabolism." },
  { planetId: 5, house: 3, effect: "beneficial", interpretation: "Intellectual siblings, good communication, musical talent.", career: "Teaching, writing, music, counseling.", relationships: "Good relationship with siblings.", health: "Good health." },
  { planetId: 5, house: 4, effect: "beneficial", interpretation: "Educated, comfortable home, wise mother. Property gains.", career: "Education, real estate, spiritual teaching.", relationships: "Harmonious family, wise mother.", health: "Good health, chest comfortable." },
  { planetId: 5, house: 5, effect: "beneficial", interpretation: "Highly creative, intelligent children, speculative gains. Dharmic.", career: "Teaching, creative arts, stock market, spirituality.", relationships: "Wise parent, good with children.", health: "Good health, strong heart." },
  { planetId: 5, house: 6, effect: "challenging", interpretation: "Debt struggles, health challenges. Overcomes obstacles through wisdom.", career: "Law, medicine, counseling, service.", relationships: "Helps others through teaching.", health: "Prone to liver Issues, diabetes." },
  { planetId: 5, house: 7, effect: "beneficial", interpretation: "Good marriage, wise partner. Successful partnerships.", career: "Public relations, consulting, partnerships.", relationships: "Marriage to wise, prosperous person.", health: "Good health." },
  { planetId: 5, house: 8, effect: "challenging", interpretation: "Hidden wisdom, interest in occult. Obstacles to inheritance.", career: "Occult, research, spiritual teaching.", relationships: "Intense spiritual connection, sudden changes.", health: "Prone to liver Issues, hidden illnesses." },
  { planetId: 5, house: 9, effect: "beneficial", interpretation: "Highly fortunate, spiritual, learned. Best placement for Jupiter.", career: "Teaching, religion, law, publishing.", relationships: "Respected guru, wise elder.", health: "Excellent health." },
  { planetId: 5, house: 10, effect: "beneficial", interpretation: "Successful career, respected, leader in field. Wise leadership.", career: "Teaching, consulting, leadership, law.", relationships: "Respected professionally.", health: "Good health, stress from responsibility." },
  { planetId: 5, house: 11, effect: "beneficial", interpretation: "Wealth through wisdom, many friends, fulfilled desires.", career: "Finance, education, investments.", relationships: "Wise counselors as friends.", health: "Good health." },
  { planetId: 5, house: 12, effect: "challenging", interpretation: "Spending on spirituality, foreign philanthropy. Wise charity.", career: "Spiritual work, charity, foreign education.", relationships: "Detachment from material relationships.", health: "Hospitalization from overindulgence." },

  // ────────── SATURN (6) ──────────
  { planetId: 6, house: 1, effect: "challenging", interpretation: "Serious, disciplined, hardworking. Late bloomer. Health concerns.", career: "Administration, manual work, engineering, service.", relationships: "Reserved in relationships, marries late.", health: "Chronic Issues, slow recovery, joint problems." },
  { planetId: 6, house: 2, effect: "challenging", interpretation: "Financial struggles, frugal, minimalistic. Hard-earned money.", career: "Manual labor, accounts, administration.", relationships: "Disciplined family life, strict parent.", health: "Teeth Issues, bones weakness." },
  { planetId: 6, house: 3, effect: "neutral", interpretation: "Hardworking, persistent, reliable. Challenges overcome through effort.", career: "Manual work, engineering, service.", relationships: "Dependable to siblings, distant.", health: "Joint Issues, arthritis tendency." },
  { planetId: 6, house: 4, effect: "challenging", interpretation: "Struggles at home, property delays. Distance from mother.", career: "Real estate delays, construction.", relationships: "Distant from mother, delayed home ownership.", health: "Bone Issues, joint pain." },
  { planetId: 6, house: 5, effect: "challenging", interpretation: "Few or no children, speculative losses. Serious creative work.", career: "Research, serious art, service.", relationships: "Disciplined with children, delay in having children.", health: "Chronic health Issues." },
  { planetId: 6, house: 6, effect: "beneficial", interpretation: "Victory over enemies, good health, disciplined. Best for Saturn.", career: "Law, administration, military, healthcare.", relationships: "Respected by rivals.", health: "Good health, disciplined lifestyle." },
  { planetId: 6, house: 7, effect: "challenging", interpretation: "Late marriage, distant spouse. Hardworking partner.", career: "Service partnerships, consulting.", relationships: "Marries late, older spouse, duty-bound relationship.", health: "Joint Issues with age." },
  { planetId: 6, house: 8, effect: "neutral", interpretation: "Long life, interest in occult. Research abilities. Inheritance delays.", career: "Research, occult, investigation.", relationships: "Intense transformative relationships.", health: "Longevity but chronic Issues." },
  { planetId: 6, house: 9, effect: "challenging", interpretation: "Struggles with beliefs, distant father. Quest for spiritual truth.", career: "Research, philosophy, law.", relationships: "Strict beliefs, challenging father relationship.", health: "Bone Issues, knee problems." },
  { planetId: 6, house: 10, effect: "neutral", interpretation: "Slow rise to success, high achievement through hard work. Authoritative.", career: "Administration, government, management.", relationships: "Career-focused, delayed home life.", health: "Stress from overwork." },
  { planetId: 6, house: 11, effect: "beneficial", interpretation: "Income from hard work, older friends. Gains through persistence.", career: "Service industry, administration.", relationships: "Older friends, helpful mentors.", health: "Good health in later life." },
  { planetId: 6, house: 12, effect: "neutral", interpretation: "Spending on service, foreign work. Monastic tendencies.", career: "Institutional work, foreign employment.", relationships: "Isolation, spiritual detachment.", health: "Hospitalization possible, joint care needed." },

  // ────────── RAHU (10) ──────────
  { planetId: 10, house: 1, effect: "challenging", interpretation: "Ambitious, unconventional, intense. Obsessive nature. Foreign connection.", career: "Foreign work, technology, unconventional fields.", relationships: "Intense relationships, unconventional approach.", health: "Prone to addictions, skin Issues, psychological stress." },
  { planetId: 10, house: 2, effect: "neutral", interpretation: "Sudden wealth, unconventional speech. Foreign income.", career: "Foreign business, import/export, finance.", relationships: "Unconventional family, foreign spouse.", health: "Eating disorders, skin Issues." },
  { planetId: 10, house: 3, effect: "neutral", interpretation: "Bold communication, foreign siblings. Adventurous.", career: "Media, technology, foreign travel.", relationships: "Distant siblings, foreign connections.", health: "Nervous system Issues." },
  { planetId: 10, house: 4, effect: "challenging", interpretation: "Foreign home, mother Issues. Unconventional living.", career: "Real estate abroad, foreign work.", relationships: "Mother may be absent or foreign.", health: "Chest Issues, psychological stress." },
  { planetId: 10, house: 5, effect: "neutral", interpretation: "Speculative gains, unconventional creativity. Foreign children.", career: "Foreign education, creative arts.", relationships: "Unconventional romance, foreign-born children.", health: "Psychological Issues, addiction risk." },
  { planetId: 10, house: 6, effect: "neutral", interpretation: "Victory over enemies through unconventional means. Foreign healthcare.", career: "Foreign medicine, technology, service.", relationships: "Unconventional service role.", health: "Healing through unconventional methods." },
  { planetId: 10, house: 7, effect: "neutral", interpretation: "Foreign spouse, unconventional marriage. Public success.", career: "International partnerships, foreign relations.", relationships: "Spouse may be foreign or from different culture.", health: "Psychosomatic Issues." },
  { planetId: 10, house: 8, effect: "neutral", interpretation: "Interest in hidden knowledge, foreign investigations. Sudden changes.", career: "Research, occult, intelligence.", relationships: "Secret foreign connections.", health: "Prone to addictions, hidden health Issues." },
  { planetId: 10, house: 9, effect: "neutral", interpretation: "Foreign philosophy, unconventional beliefs. Foreign teachers.", career: "International education, publishing, travel.", relationships: "Foreign gurus, different belief systems.", health: "Travel-related health Issues." },
  { planetId: 10, house: 10, effect: "neutral", interpretation: "Rapid career rise, unconventional success. Foreign work.", career: "International business, technology, media.", relationships: "Career success from unconventional methods.", health: "Stress from rapid success." },
  { planetId: 10, house: 11, effect: "neutral", interpretation: "Foreign income, unconventional friends. Fulfilled desires abroad.", career: "Import/export, foreign business.", relationships: "Foreign friends, unconventional social circle.", health: "Good health." },
  { planetId: 10, house: 12, effect: "beneficial", interpretation: "Spiritual liberation, foreign travel. Actually beneficial for Rahu.", career: "Spiritual work, foreign institutions.", relationships: "Detachment from materialism.", health: "Hospitalization abroad, eventual healing." },

  // ────────── KETU (11) ──────────
  { planetId: 11, house: 1, effect: "challenging", interpretation: "Spiritual, detached, unconventional. Piercing insight.", career: "Spiritual work, research, technology.", relationships: "Detached, non-attached to relationships.", health: "Prone to mysterious illnesses, psychological depth." },
  { planetId: 11, house: 2, effect: "challenging", interpretation: "Irregular finances, spiritual speech. Detached from wealth.", career: "Spiritual teaching, unconventional work.", relationships: "Detached from family materialism.", health: "Eating irregularities." },
  { planetId: 11, house: 3, effect: "neutral", interpretation: "Cutting communication, research skills. Detached from siblings.", career: "Research, technology, spiritual writing.", relationships: "Distant siblings, solitary nature.", health: "Nerve Issues." },
  { planetId: 11, house: 4, effect: "challenging", interpretation: "Detached from home, mother may be spiritual. Unconventional living.", career: "Research, technology from home.", relationships: "Distant mother, peace through solitude.", health: "Mental peace through meditation." },
  { planetId: 11, house: 5, effect: "neutral", interpretation: "Detached from children, spiritual creativity. Mystical intelligence.", career: "Spiritual teaching, creative research.", relationships: "Detached romance, spiritual parenting.", health: "Good health through discipline." },
  { planetId: 11, house: 6, effect: "beneficial", interpretation: "Victory over enemies through detachment. Healer.", career: "Healing, therapy, research, medicine.", relationships: "Helps others through spiritual means.", health: "Good health, healing ability." },
  { planetId: 11, house: 7, effect: "neutral", interpretation: "Detached from marriage. Spiritual partnership.", career: "Spiritual counseling, therapy.", relationships: "Spiritual marriage, little physical attachment.", health: "Psychosomatic health tied to partner." },
  { planetId: 11, house: 8, effect: "neutral", interpretation: "Deep mystical knowledge, interest in occult. Research abilities.", career: "Research, occult, psychology.", relationships: "Intense but detached relationships.", health: "Mysterious health conditions." },
  { planetId: 11, house: 9, effect: "neutral", interpretation: "Spiritual wisdom, detachment from religion. Philosophical.", career: "Spiritual teaching, philosophy.", relationships: "Detached from traditional beliefs.", health: "Good spiritual health." },
  { planetId: 11, house: 10, effect: "neutral", interpretation: "Career in spiritual or research fields. Unconventional success.", career: "Technology, research, spiritual teaching.", relationships: "Detached career focus.", health: "Good health." },
  { planetId: 11, house: 11, effect: "neutral", interpretation: "Detached from friends, gains through spirituality.", career: "Spiritual work, research.", relationships: "Solo nature, few friends.", health: "Good health." },
  { planetId: 11, house: 12, effect: "beneficial", interpretation: "Spiritual liberation, enlightenment. Best for Ketu.", career: "Monastic, spiritual, charitable work.", relationships: "Complete detachment, spiritual freedom.", health: "Mental peace, spiritual health." },
];

export function getPlanetInHouseInterpretation(planetId: number, house: number): PlanetInHouseEntrySimple | null {
  return PLANET_IN_HOUSE.find(e => e.planetId === planetId && e.house === house) || null;
}

export function getAllPlanetInHouseRules(): PlanetInHouseEntrySimple[] {
  return PLANET_IN_HOUSE;
}
